version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    # Raise pull requests for version updates
    open-pull-requests-limit: 10
    # Group all updates into a single pull request
    groups:
      dependencies:
        patterns:
          - "*"
