export enum MissionStatut {
  EN_ATTENTE = 'EN_ATTENTE',
  INVITE = 'INVITE',
  ASSIGNEE = 'ASSIGNEE',
  EN_COURS = 'EN_COURS',
  TERMINEE = 'TERMINEE',
  ANNULEE = 'ANNULEE',
  SUSPENDUE = 'SUSPENDUE'
}
